# Generated by Django 3.0.2 on 2020-02-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='state',
            field=models.CharField(choices=[('bodega', 'bodega'), ('transito', 'transito'), ('entregado', 'entregado')], max_length=10),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
