# Generated by Django 3.0.2 on 2020-02-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_auto_20200207_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='state',
            field=models.CharField(choices=[('bodega', 'bodega'), ('transito', 'transito'), ('entregado', 'entregado')], default='bodega', max_length=10),
        ),
    ]
